area/docs: ["/docs"]
area/ui: ["/ui", "/provider-ui"]
area/ci: ["/.github"]
component/mesheryctl: ["/mesheryctl"]
component/api: ["/handlers"]
language/go: ["*.go"]
language/markdown: ["*.md"]
language/javascript: ["*.js"]
# backend: ["/app", "*.rb"]
# legal: ["LICENSE*", "NOTICES*"]

