version: '3'
services:
  meshery:
    image: layer5/meshery
    environment:
      - "SAAS_BASE_URL=https://meshery.layer5.io"
      - "EVENT=mesheryLocal"
    ports:
      - "9081:8080"
  meshery-istio:
    image: layer5/meshery-istio
    ports:
      - "10000:10000"
  meshery-linkerd:
    image: layer5/meshery-linkerd
    ports:
      - "10001:10001"
