version: '3'
services:
  meshery:
    image: layer5/meshery
    environment:
      - "SAAS_BASE_URL=https://meshery.layer5.io"
      - "EVENT=mesheryLocal"
    ports:
      - "9081:8080"
    depends_on:
      - fortio
  meshery-istio:
    image: layer5/meshery-istio
    ports:
      - "10000:10000"

