version: '3'
services:
  meshery:
    image: layer5/meshery:stable-latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - "SAAS_BASE_URL=https://meshery.layer5.io"
      - "ADAPTER_URLS=meshery-istio:10000"
      - "EVENT=mesheryLocal"
    volumes:
      - $HOME/.kube:/home/appuser/.kube:ro
    ports:
      - "9081:8080"
  meshery-istio:
    image: layer5/meshery-istio:stable-latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "10000:10000"
  watchtower:
    image: v2tec/watchtower
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --label-enable
volumes:
  meshery-config:
