apiVersion: v2
name: meshery
description: Meshery chart for deploying Meshery and Meshery's adapters.
icon: https://github.com/layer5io/meshery/blob/master/ui/public/static/img/meshery-logo/meshery-logo.svg
kubeVersion: 
keywords:
  - meshery
  - mesheryistio
  - mesherylinkerd
  - mesheryconsul
  - meshery-kuma
  - meshery-osm
source: 
  - https://github.com/layer5io/meshery

engine: gotpl

deprecated: false

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 1.3.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
# TODO: Need to confirm the image version
appVersion: stable-latest


dependencies:
- name: mesheryistio
  version: 1.0.0
  condition: mesheryistio.enabled
- name: mesherylinkerd
  version: 1.0.0
  condition: mesherylinkerd.enabled
- name: mesheryconsul
  version: 1.0.0
  condition: mesheryconsul.enabled
- name: meshery-kuma
  version: 1.0.0
  condition: meshery-kuma.enabled
- name: meshery-osm
  version: 1.0.0
  condition: meshery-osm.enabled
- name: meshery-nsm
  version: 1.0.0
  condition: meshery-nsm.enabled

maintainers:
  - name: Layer5 Authors
    email: community@layer5.io
  - name: aisuko
    email: urakiny@gmail.com
  - name: leecalcote
    email: lee.calcote@layer5.io