apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: dynamo
  name: dynamo
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: dynamo
    spec:
      containers:
      - image: instructure/dynamo-local-admin
        name: dynamo
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
status: {}
