apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: meshery-saas
  name: meshery-saas
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: meshery-saas
    spec:
      containers:
      - env:
        - name: AWS_ACCESS_KEY_ID
          value: blah
        - name: AWS_ENDPOINT
          value: http://dynamo:8000
        - name: AWS_REGION
          value: eu-west-1
        - name: AWS_SECRET_ACCESS_KEY
          value: blah
        - name: GITHUBKEY
        - name: GITHUBSECRET
        - name: HOST
          value: meshery-saas
        - name: TWITTERKEY
        - name: TWITTERSECRET
        image: layer5/meshery-saas
        name: meshery-saas
        ports:
        - containerPort: 9876
        resources: {}
      restartPolicy: Always
status: {}
