apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: meshery
  name: meshery
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: meshery
    spec:
      containers:
      - env:
        - name: EVENT
          value: mesheryLocal
        - name: FORTIO_URL
          value: http://fortio:8080/fortio/
        - name: SAAS_BASE_URL
          value: http://meshery-saas:9876
        image: layer5/meshery
        name: meshery
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
