apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: meshery-osm
  name: meshery-osm
spec:
  selector:
    matchLabels:
      io.kompose.service: meshery-osm
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: meshery-osm
    spec:
      serviceAccount: meshery
      containers:
      - image: layer5/osm-consul:stable-latest
        name: meshery-osm
        ports:
        - containerPort: 10010
        resources: {}
      restartPolicy: Always
status: {}
