name: Error Code Reference Publisher
on:
  push:
    branches:
      - 'master'
    paths:
      - '**.go'

jobs:
  Update-error-ref:
    name: Error codes utility
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ secrets.GO_VERSION }}

      - name: Update error reference for Meshery Server
        run: |
          go run github.com/layer5io/meshkit/cmd/errorutil -d . analyze --skip-dirs mesheryctl
          echo '{ "errors_export": "" }' | jq --slurpfile export ./errorutil_errors_export.json '.errors_export = $export[0]' > ./docs/_data/errorref/meshery-server_errors_export.json

      - name: Update error reference for Mesheryctl
        run: |
          cd ./mesheryctl
          go run github.com/layer5io/meshkit/cmd/errorutil -d . analyze
        # temporarily commenting cuz this will fail until we run the utilty once on mesheryctl
        # echo '{ "errors_export": "" }' | jq --slurpfile export ./errorutil_errors_export.json '.errors_export = $export[0]' > ../docs/_data/errorref/mesheryctl_errors_export.json

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: l5io
          commit_user_email: ci@layer5.io
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit_options: '--signoff'
          commit_message: "[Docs] Error Code Reference: update Meshery server and mehseryctl error codes"
