name: Release Notes Publisher

on:
  push:
    branches:
      - '!*'
    tags:
      - 'v*'

jobs:
  create_release_notes_pr:
      runs-on: ubuntu-latest
      steps:
        - name: Drafting release
          id: release_drafter
          uses: release-drafter/release-drafter@v5
          with:
            config-name: release-drafter.yml
          env:
            GITHUB_TOKEN: ${{ secrets.RELEASEDRAFTER_PAT }}

        - name: Checkout
          uses: actions/checkout@v2
          with:
            ref: 'master'
            token: ${{ secrets.RELEASEDRAFTER_PAT }}

        - name: Write release notes to markdown file
          run: |
            echo "Tag: " ${{ steps.release_drafter.outputs.tag_name }}
            printf '%b\n' "---\nlayout: release\ndate: $(date +'%Y-%m-%d')\ntag: ${{ steps.release_drafter.outputs.tag_name }}\n---\n\n${{ steps.release_drafter.outputs.body }} " > ./docs/_releases/${{ steps.release_drafter.outputs.tag_name }}.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: l5io
          commit_user_email: ci@layer5.io
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit_options: '--signoff'
          commit_message: '[Docs] Release Notes for Meshery ${{ steps.release_drafter.outputs.tag_name }}'
