name: Release Notes Publisher

on: [push, pull_request]

jobs:
  write_release_notes:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - name: Drafting release
        id: release_drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: release-drafter.yml

      - name: Checkout release notes
        uses: actions/checkout@v2

      - name: Write release notes to markdown file
        id: md_writer
        run: |
          printf '%b\n' "---\nlayout: default\n---\n\n${{ steps.release_drafter.outputs.body }} " > ./docs/_releases/${{ steps.release_drafter.outputs.tag_name }}.md

      - name: Cat release notes (DELETE ME)
        run: ls -la ./docs/_releases/

  create_release_notes_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.RELEASEDRAFTER_PAT }}
          commit-message: "Created release note file ${{ steps.release_drafter.outputs.tag_name }}.md"
          committer: l5io <ci@layer5.io>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: true
          branch: docs/automated-release-notes
          delete-branch: true
          base: master
          title: '[Docs] Release Notes for Meshery ${{ steps.release_drafter.outputs.tag_name }}'
          body: |
            An auto-generated pull request to document release notes for Meshery ${{ steps.release_drafter.outputs.tag_name }}
          labels: |
            area/ci
            kind/chore
          # assignees:
          # reviewers:
          team-reviewers: |
            release-team
            maintainers
          # milestone: 1
          draft: false

      - name: Verify PR
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
