name: Notify slack
on: watch
jobs:
  star-notify:
    name: Notify slack on star
    runs-on: ubuntu-latest
    steps:
    - name: Notify slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"CLVT4TSG4\",\"text\":\"Someone has starred Meshery!\"}'
        run: STAR="$(curl -s https://github.com/layer5io/meshery | nokogiri -e 'puts $_.search('\''a'\'').text' | sed -n 95p | awk '{print $1}')"
        run: echo "Now at $STAR stars"
